name: Python CI

#Trigeer the workflow on any push to the main branch or pull trequest
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            #Chcek out the code form the repo
            - name: Check out code
              uses: actions/checkout@v2

            #Step2:Set up the Python envi
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'

            #Step3:INstall req
            - name: Install dependencies
              run:
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            #Step4:Run tests
            - name: Run tests
              run: pytest

